
theme: jekyll-theme-minimal
title: Harpriya
logo: assets/images/Profile Picture.JPG
description: Bookmark this to keep an eye on my project updates!
show_downloads: True
plugins:
- jekyll-remote-theme 
